import { SlideTheme } from "../types";

export const SLIDE_THEMES: SlideTheme[] = [
  {
    id: "clean-bright-white",
    name: "Trắng Sáng Tự Nhiên (#FFFFFF)",
    bgGradient: "from-[#ffffff] to-[#ffffff]",
    cardBg: "bg-white text-[#111111] shadow-[0_4px_20px_rgba(0,0,0,0.06)] border border-stone-200",
    textColor: "text-[#111111]",
    accentBadge: "bg-[#111111] text-white font-bold",
    borderStyle: "border-stone-200",
    previewColor: "#ffffff",
  },
  {
    id: "studio-light-gray",
    name: "Xám Sáng Studio (#F8F9FA)",
    bgGradient: "from-[#f8f9fa] to-[#f1f3f5]",
    cardBg: "bg-white text-[#111111] shadow-[0_4px_20px_rgba(0,0,0,0.08)] border border-slate-200",
    textColor: "text-[#111111]",
    accentBadge: "bg-[#D9383A] text-white font-bold",
    borderStyle: "border-slate-200",
    previewColor: "#f8f9fa",
  },
  {
    id: "minimalist-cream",
    name: "Be Kem Nhạt (#FDFBF7)",
    bgGradient: "from-[#fdfbf7] to-[#f9f5ec]",
    cardBg: "bg-white text-[#111111] shadow-[0_4px_20px_rgba(0,0,0,0.06)] border border-stone-200",
    textColor: "text-[#111111]",
    accentBadge: "bg-[#1b4332] text-white font-bold",
    borderStyle: "border-stone-300",
    previewColor: "#fdfbf7",
  },
  {
    id: "pastel-peach",
    name: "Cam Đào Viral (#FFF5F0)",
    bgGradient: "from-[#fff5f0] to-[#ffede5]",
    cardBg: "bg-white text-[#111111] shadow-md border border-orange-200",
    textColor: "text-[#111111]",
    accentBadge: "bg-orange-600 text-white font-bold",
    borderStyle: "border-orange-200",
    previewColor: "#ffe5d9",
  },
  {
    id: "matcha-fresh",
    name: "Matcha Botanical (#F4F9F4)",
    bgGradient: "from-[#f4f9f4] to-[#eaf3ea]",
    cardBg: "bg-white text-[#111111] shadow-md border border-emerald-200",
    textColor: "text-[#111111]",
    accentBadge: "bg-emerald-800 text-white font-bold",
    borderStyle: "border-emerald-200",
    previewColor: "#e0ede0",
  },
  {
    id: "dark-luxury",
    name: "Dark Studio Quyền Lực",
    bgGradient: "from-[#111827] via-[#0b0f19] to-[#030712]",
    cardBg: "bg-slate-900 text-slate-100 shadow-xl border border-slate-800",
    textColor: "text-slate-100",
    accentBadge: "bg-pink-500 text-white font-bold",
    borderStyle: "border-slate-800",
    previewColor: "#0f172a",
  },
];
